name: PlatformIO Build

on:
  push:
    branches: [ main ]  # Запускать при пуше в ветку main
  pull_request:         # И при пул-реквестах

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install PlatformIO CLI
        run: |
          pip install platformio

      - name: Restore PlatformIO Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.platformio
            .pio
          key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}

      - name: Build Project with logs
        run: |
          pio run -v  # Компиляция проекта
      - name: Build Project without logs
        run: |
          pio run     # Компиляция проекта
              - name: Build Project


